# Generated by Django 5.1.4 on 2025-01-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0002_customuser_address_customuser_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
