# Generated by Django 5.1.4 on 2025-01-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0003_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
