# Generated by Django 5.1.3 on 2025-01-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0005_alter_message_slug_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
